title: Translations Archive
description: ชั้นเก็บงานแปลเก่า ๆ ของ Akara
markdown: kramdown
google_analytics:
theme: jekyll-theme-minimal
include: [ 'LICENSE.md', 'TRANSLATIONS_LICENSE.md ]
plugins:
   - jekyll-seo-tag
